version: '3'
services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A my_app_name worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
  flower:
    build: .
    command: celery -A my_app_name flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis